services:
  promocode-factory-rabbit:
    image: rabbitmq:3-management
    restart: always
    hostname: rabbitmqhost    
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 5s
      
  promocode-factory-administration-db:
    image: "postgres:17.4"
    container_name: 'promocode-factory-administration-db'
    restart: always 
    ports:
      - "5433:5432"
    environment: 
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: promocode_factory_administration_db
    healthcheck:
      test: ["CMD-SHELL", "su", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

  promocode-factory-administration-api:
    build: src/Pcf.Administration/
    container_name: 'promocode-factory-administration-api'
    ports:
      - "8091:8080"
    environment:
      - ConnectionStrings__PromocodeFactoryAdministrationDb=Host=promocode-factory-administration-db;Database=promocode_factory_administration_db;Username=postgres;Password=docker
    depends_on:
      promocode-factory-rabbit:
        condition: service_healthy
      promocode-factory-administration-db:
        condition: service_healthy

  promocode-factory-receiving-from-partner-db:
    image: "postgres:latest"
    container_name: 'promocode-factory-receiving-from-partner-db'
    restart: always 
    ports:
      - "5434:5432"
    environment: 
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: promocode_factory_receiving_from_partner_db
    healthcheck:
      test: ["CMD-SHELL", "su", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

  promocode-factory-receiving-from-partner-api:
    build: src/Pcf.ReceivingFromPartner/
    container_name: 'promocode-factory-receiving-from-partner-api'
    ports:
      - "8092:8080"
    environment:
      - "ConnectionStrings__PromocodeFactoryReceivingFromPartnerDb=Host=promocode-factory-receiving-from-partner-db;Database=promocode_factory_receiving_from_partner_db;Username=postgres;Password=docker"
      - "IntegrationSettings:GivingToCustomerApiUrl=http://promocode-factory-giving-to-customer-api"    
      - "IntegrationSettings:AdministrationApiUrl=http://promocode-factory-administration-api"       
    depends_on:
      promocode-factory-rabbit:
        condition: service_healthy
      promocode-factory-receiving-from-partner-db:
        condition: service_healthy

  promocode-factory-giving-to-customer-db:
    image: "postgres:latest"
    container_name: 'promocode-factory-giving-to-customer-db'
    restart: always 
    ports:
      - "5435:5432"
    environment: 
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: promocode_factory_giving_to_customer_db
    healthcheck:
      test: ["CMD-SHELL", "su", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

  promocode-factory-giving-to-customer-api:
    build: src/Pcf.GivingToCustomer/
    container_name: 'promocode-factory-giving-to-customer-api'
    ports:
      - "8093:8080"
    environment:
      - "ConnectionStrings__PromocodeFactoryGivingToCustomerDb=Host=promocode-factory-giving-to-customer-db;Database=promocode_factory_giving_to_customer_db;Username=postgres;Password=docker"          
    depends_on:
      promocode-factory-rabbit:
        condition: service_healthy
      promocode-factory-giving-to-customer-db:
        condition: service_healthy